
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=create

spring.security.oauth2.client.registration.github.client-id = ${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret = ${GITHUB_CLIENT_SECRET}
# TODO: Lägg till OAuth2 config här (Google/GitHub)
